export default [
  { name: 'grin', emoji: '😀' },
  { name: 'thumbs_up', emoji: '👍' },
  { name: 'thumbs_down', emoji: '👎' },
  { name: 'red_heart', emoji: '❤️' },
  { name: 'fire', emoji: '🔥' },
  { name: 'face_with_tears_of_joy', emoji: '😂' },
  { name: 'rolling_on_the_floor_laughing', emoji: '🤣' },
  { name: 'pouting_face', emoji: '😡' },
  { name: 'party_popper', emoji: '🎉' },
  { name: 'ok_hand', emoji: '👌' },
  { name: 'smiling_face_with_heart-eyes', emoji: '😍' },
  { name: 'smiling_face_with_halo', emoji: '😇' },
  { name: 'man_gesturing_ok', emoji: '🙆‍♂️' },
  { name: 'loudly_crying_face', emoji: '😭' },
  { name: 'face_with_rolling_eyes', emoji: '🙄' },
  { name: 'check_mark', emoji: '✅' },
  { name: 'rainbow', emoji: '🌈' },
  { name: 'thinking_face', emoji: '🤔' },
  { name: 'eyes', emoji: '👀' },
  { name: 'face_holding_back_tears', emoji: '🥹' },
]