import helpers from '../core/helpers'

const arr = [
  { symbol: 'USDT', kr: '테더', en: 'Tether' },
  { symbol: 'BNB', kr: '바이낸스 코인', en: 'Binance Coin' },
  { symbol: 'BUSD', kr: '바이낸스 USD', en: 'Binance USD' },
  { symbol: 'USDC', kr: 'USD 코인', en: 'USD Coin' },
  { symbol: 'WBTC', kr: '랩드 비트코인', en: 'Wrapped Bitcoin' },
  { symbol: 'KLAY', kr: '클레이튼', en: 'Klaytn' },
  { symbol: 'GUSD', kr: '제미니 USD', en: 'Gemini USD' },
  { symbol: 'PAX', kr: '팩소스 스탠다드', en: 'Paxos Standard' },
  { symbol: 'YFI', kr: '연 파이낸스', en: 'Yearn Finance' },
  { symbol: 'EGLD', kr: '엘론드', en: 'Elrond' },
  { symbol: 'KSM', kr: '쿠사마', en: 'Kusama' },
  { symbol: 'BAL', kr: '밸런서', en: 'Balancer' },
  { symbol: 'MBX', kr: '마브렉스', en: 'Marblex' },
  { symbol: 'XVS', kr: '비너스', en: 'Venus' },
  { symbol: 'CAKE', kr: '팬케이크스왑', en: 'PancakeSwap' },
  { symbol: 'UMA', kr: '우마', en: 'Uma' },
  { symbol: 'ALICE', kr: '마이네이버앨리스', en: 'MyNeighborAlice' },
  { symbol: 'DAO', kr: '다오메이커', en: 'DAO Maker' },
  { symbol: 'NPT', kr: '네오핀', en: 'Neopin' },
  { symbol: 'SUSHI', kr: '스시스왑', en: 'SushiSwap' },
  { symbol: 'TITAN', kr: '타이탄스왑', en: 'TitanSwap' },
  { symbol: 'CTK', kr: '셴투', en: 'Shentu' },
  { symbol: 'TAVA', kr: '알타바', en: 'ALTAVA' },
  { symbol: 'BEL', kr: '벨라프로토콜', en: 'Bella Protocol' },
  { symbol: 'C98', kr: '코인98', en: 'Coin98' },
  { symbol: 'UOS', kr: '울트라', en: 'Ultra' },
  { symbol: 'BOBA', kr: '보바 네트워크', en: 'Boba Network' },
  { symbol: 'VALOR', kr: '밸러토큰', en: 'Valor Token' },
  { symbol: 'ARW', kr: '아로와나토큰', en: 'Arowana Token' },
  { symbol: 'FRONT', kr: '프론티어', en: 'Frontier' },
  { symbol: 'SWAP', kr: '트러스트스왑', en: 'TrustSwap' },
  { symbol: 'SPRT', kr: '스포티움', en: 'Sportium' },
  { symbol: 'WOO', kr: '우네트워크', en: 'WOO Network' },
  { symbol: 'SOFI', kr: '라이파이낸스', en: 'RAI Finance' },
  { symbol: 'ORC', kr: '오르빗 체인', en: 'Orbit Chain' },
  { symbol: 'ANV', kr: '애니버스', en: 'ANIVERSE' },
  { symbol: 'EFI', kr: '이피니티토큰', en: 'Efinity Token' },
  { symbol: 'CTXC', kr: '코르텍스', en: 'Cortex' },
  { symbol: 'REN', kr: '렌', en: 'Ren' },
  { symbol: 'COLA', kr: '콜라워크', en: 'Colawork' },
  { symbol: 'REQ', kr: '리퀘스트', en: 'Request' },
  { symbol: 'DFA', kr: '디파인', en: 'DeFine' },
  { symbol: 'COTI', kr: '코티', en: 'COTI' },
  { symbol: 'WOZX', kr: '이포스', en: 'Efforce' },
  { symbol: 'WICC', kr: '웨이키체인', en: 'WaykiChain' },
  { symbol: 'MXC', kr: '머신익스체인지코인', en: 'MXC' },
  { symbol: 'DVI', kr: '디비전', en: 'Dvision Network' },
  { symbol: 'SIX', kr: '식스', en: 'SIX' },
  { symbol: 'WOM', kr: '왐 프로토콜', en: 'WOM Protocol' },
  { symbol: 'GALA', kr: '갈라', en: 'Gala' },
  { symbol: 'BOA', kr: '보스 아고라', en: 'BOSAGORA' },
  { symbol: 'XYM', kr: '심볼', en: 'Symbol' },
  { symbol: 'CENNZ', kr: '센트럴리티', en: 'CENNZnet' },
  { symbol: 'APM', kr: '에이피엠 코인', en: 'apM Coin' },
  { symbol: 'EVZ', kr: '이브이지', en: 'EVZ' },
  { symbol: 'POLA', kr: '폴라리스 쉐어', en: 'Polaris Share' },
  { symbol: 'CSPR', kr: '캐스퍼', en: 'Casper' },
  { symbol: 'XNO', kr: '제노토큰', en: 'Xeno Token' },
  { symbol: 'ASM', kr: '어셈블프로토콜', en: 'Assemble Protocol' },
  { symbol: 'GHX', kr: '게이머코인', en: 'GamerCoin' },
  { symbol: 'CELR', kr: '셀러네트워크', en: 'Celer Network' },
  { symbol: 'CON', kr: '코넌', en: 'CONUN' },
  { symbol: 'MEV', kr: '미버스', en: 'MEVerse' },
  { symbol: 'ATOLO', kr: '라이즌', en: 'RIZON' },
  { symbol: 'ADP', kr: '어댑터 토큰', en: 'Adappter Token' },
  { symbol: 'MAP', kr: '맵프로토콜', en: 'MAP Protocol' },
  { symbol: 'ACH', kr: '알케미페이', en: 'Alchemy Pay' },
  { symbol: 'BLY', kr: '블로서리', en: 'Blocery' },
  { symbol: 'GOM2', kr: '고머니2', en: 'AnimalGo' },
  { symbol: 'CYCLUB', kr: '싸이클럽', en: 'Cyclub' },
  { symbol: 'EGG', kr: '네스트리', en: 'Nestree' },
  { symbol: 'JASMY', kr: '재스미코인', en: 'Jasmy' },
  { symbol: 'TRV', kr: '트러스트버스', en: 'TrustVerse' },
  { symbol: 'WIKEN', kr: '위드', en: 'Project WITH' },
  { symbol: 'VELO', kr: '벨로프로토콜', en: 'Velo' },
  { symbol: 'MVC', kr: '마일벌스', en: 'MileVerse' },
  { symbol: 'COS', kr: '콘텐토스', en: 'Contentos' },
  { symbol: 'TDROP', kr: '쎄타드랍', en: 'ThetaDrop' },
  { symbol: 'SOC', kr: '소다코인', en: 'Soda Coin' },
  { symbol: 'BIOT', kr: '바이오패스포트', en: 'BioPassport Token' },
  { symbol: 'AWO', kr: '에이아이워크', en: 'AiWork' },
  { symbol: 'VRA', kr: '베라시티', en: 'Verasity' },
  { symbol: 'MIX', kr: '믹스마블', en: 'MixMarvel' },
  { symbol: 'CKB', kr: '너보스', en: 'Nervos Network' },
  { symbol: 'EL', kr: '엘리시아', en: 'ELYSIA' },
  { symbol: 'XPR', kr: '프로톤', en: 'Proton' },
  { symbol: 'TEMCO', kr: '템코', en: 'TEMCO' },
  { symbol: 'AMO', kr: '아모코인', en: 'AMO Coin' },
  { symbol: 'HIBS', kr: '하이블럭스', en: 'Hiblocks' },
  { symbol: 'FIT', kr: '300피트 네트워크', en: '300FIT NETWORK' },
  { symbol: 'NFT', kr: '에이피이앤에프티', en: 'APENFT' },
  { symbol: 'ALT', kr: '아치루트', en: 'Archloot' },
  { symbol: 'AZIT', kr: '아지트', en: 'Azit' },
  { symbol: 'FITFI', kr: '스텝앱', en: 'Step App' },
  { symbol: 'XCN', kr: '체인', en: 'Chain' },
  { symbol: 'GXA', kr: '갤럭시아', en: 'Galaxia' },
  { symbol: 'PEPE', kr: '페페', en: 'Pepe' },
  { symbol: 'LDO', kr: '리도 다오', en: 'Lido DAO' },
  { symbol: 'CFX', kr: '컨플럭스', en: 'Conflux' },
  { symbol: 'GMX', kr: '지엠엑스', en: 'GMX' },
  { symbol: 'OP', kr: '옵티미즘', en: 'Optimism' },
  { symbol: 'HOOK', kr: '훅트 프로토콜', en: 'Hooked Protocol' },
  { symbol: 'OAS', kr: '오아시스', en: 'Oasys' },
  { symbol: 'FLZ', kr: '펠라즈', en: 'Fellaz' },
  { symbol: 'SFP', kr: '세이프팔', en: 'SafePal' },
  { symbol: 'FANC', kr: '팬시', en: 'FanC' },
  { symbol: 'LBL', kr: '레이블 파운데이션', en: 'LABEL Foundation' },
  { symbol: 'RPL', kr: '로켓풀', en: 'Rocket Pool' },
  { symbol: 'DAR', kr: '마인즈 오브 달라니아', en: 'Mines of Dalarnia' },
  { symbol: 'VIX', kr: '빅스코', en: 'VIXCO' },
  { symbol: 'FLOKI', kr: '플로키', en: 'FLOKI' },
  { symbol: 'XPLA', kr: '엑스플라', en: 'XPLA' },
  { symbol: 'STAT', kr: '스탯', en: 'STAT' },
  { symbol: 'DYDX', kr: '디와이디엑스', en: 'DYDX' },
  { symbol: 'FLR', kr: '플레어', en: 'Flare' },
  { symbol: 'LN', kr: '링크', en: 'LINK' },
  { symbol: 'GRACY', kr: '그레이시', en: 'GRACY' },
  { symbol: 'WLD', kr: '월드코인', en: 'Worldcoin' },
  { symbol: 'ENTC', kr: '엔터버튼', en: 'ENTERBUTTON' },
  { symbol: 'NCT', kr: '폴리스웜', en: 'PolySwarm' },
  { symbol: 'LM', kr: '레저메타', en: 'LeisureMeta' },
  { symbol: 'MAV', kr: '매버릭 프로토콜', en: 'Maverick Protocol' },
  { symbol: 'CRTS', kr: '크레이토스', en: 'Cratos' },
  { symbol: 'AGIX', kr: '싱귤래리티넷', en: 'SingularityNET' },
  { symbol: 'WNCG', kr: '나인크로니클', en: 'Nine Chronicles' },
  { symbol: 'GRND', kr: '슈퍼워크', en: 'SuperWalk' },
  { symbol: 'FTM', kr: '팬텀', en: 'Fantom' },
  { symbol: 'FET', kr: '페치', en: 'Fetch.ai' },
  { symbol: 'EVER', kr: '에버스케일', en: 'Everscale' },
  { symbol: 'STG', kr: '스타게이트 파이낸스', en: 'Stargate Finance' },
  { symbol: 'FNSA', kr: '핀시아', en: 'FINSCHIA' },
]

const o = {}
arr.forEach(item => o[item.symbol] = {
  symbol: item.symbol,
  kr: item.kr,
  en: item.en,
  thumb: helpers.useCdn(`images/symbols/${item.symbol}.png`)
})
export default o