-- 2026-08-19 시점 운영 MySQL(coinsect)의 구조를 PostgreSQL로 옮긴 기준선.
--
-- 이 파일이 스키마의 유일한 진실이다. TypeORM 마이그레이션은 폐기했다 - migrations
-- 테이블(30행)과 파일(31개)이 이미 어긋나 있어 추적 가치가 없었다.
-- 이후 변경은 002_*.sql, 003_*.sql로 붙인다.
--
-- 적용: psql -U coinsect -d coinsect -f schema/001_baseline.sql

SET client_min_messages = warning;
SET timezone = 'UTC';

-- MySQL의 ON UPDATE CURRENT_TIMESTAMP(6)에 대응하는 문법이 PostgreSQL에는 없다.
-- TypeORM의 @UpdateDateColumn은 save() 경로에서만 확실히 동작하는데, 델타 동기화가
-- updated_at을 기준으로 삼으므로 DB 레벨 보장이 필요하다.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------- 사용자

CREATE TABLE users (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz,
  email           varchar(255) NOT NULL,
  password        varchar(255),
  phone           varchar(255),
  role            varchar(255) NOT NULL DEFAULT 'user',
  auth            varchar(255),
  sign_in_count   integer NOT NULL DEFAULT 0,
  last_sign_in    timestamptz,
  last_sign_in_ip varchar(255),
  deactivated_at  timestamptz
);

CREATE TABLE profiles (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  birthday   timestamptz,
  name       varchar(255),
  nickname   varchar(255) NOT NULL,
  user_id    integer,
  gender     varchar(255),
  image      varchar(255),
  CONSTRAINT uq_profiles_user UNIQUE (user_id),
  CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE auth_tokens (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  token      varchar(255) NOT NULL,
  provider   varchar(255) NOT NULL,
  user_id    integer,
  CONSTRAINT uq_auth_tokens_user UNIQUE (user_id),
  CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE user_securities (
  id                           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at                   timestamptz NOT NULL DEFAULT now(),
  updated_at                   timestamptz NOT NULL DEFAULT now(),
  deleted_at                   timestamptz,
  password_reset_token         varchar(255),
  password_reset_token_sent_at timestamptz,
  user_id                      integer,
  CONSTRAINT uq_user_securities_user UNIQUE (user_id),
  CONSTRAINT fk_user_securities_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE banned_users (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  ip         varchar(255),
  reason     text,
  until      timestamptz DEFAULT now(),
  user_id    integer,
  token      varchar(255),
  CONSTRAINT uq_banned_users_user UNIQUE (user_id),
  CONSTRAINT fk_banned_users_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ---------------------------------------------------------------- 게시판

CREATE TABLE boards (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  type        varchar(255),
  title       varchar(255),
  description varchar(255)
);

-- posts.user_id에는 FK가 없다. 엔티티가 createForeignKeyConstraints: false로 선언해
-- 운영 MySQL에도 제약이 걸려 있지 않다.
CREATE TABLE posts (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  title       varchar(255),
  content     text NOT NULL,
  views       integer NOT NULL DEFAULT 0,
  nickname    varchar(255) NOT NULL,
  ip          varchar(255),
  user_id     integer,
  board_id    integer,
  sharing_key varchar(255),
  password    varchar(255),
  post_type   varchar(255) NOT NULL DEFAULT 'normal',
  last_edit   timestamptz,
  tags        varchar(255),
  CONSTRAINT fk_posts_board FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE SET NULL
);
CREATE INDEX idx_posts_board_fk ON posts (board_id);
CREATE INDEX idx_posts_sharing_key ON posts (sharing_key);
CREATE INDEX idx_posts_main ON posts (deleted_at, created_at DESC, board_id);
CREATE INDEX idx_board_posts ON posts (board_id, deleted_at, created_at DESC);

CREATE TABLE replies (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  content    text NOT NULL,
  nickname   varchar(255) NOT NULL,
  ip         varchar(255),
  password   varchar(255),
  post_id    integer,
  parent_id  integer,
  user_id    integer,
  last_edit  timestamptz,
  CONSTRAINT fk_replies_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE SET NULL,
  CONSTRAINT fk_replies_parent FOREIGN KEY (parent_id) REFERENCES replies(id) ON DELETE SET NULL
);
CREATE INDEX idx_replies_post ON replies (post_id);
CREATE INDEX idx_replies_parent ON replies (parent_id);

-- ---------------------------------------------------------------- 채팅
--
-- messages_202605는 2026-05-20에 messages를 rename하고 새 messages를 만든 흔적이다.
-- 두 테이블의 id 범위가 1부터 겹친다(messages 1~1944, messages_202605 1~878422).
-- 코드에서 아카이브를 읽는 곳은 없지만 reactions.message_id의 FK 대상이므로
-- 운영과 1:1로 보존한다.

CREATE TABLE messages_202605 (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz,
  ip              varchar(255) NOT NULL,
  type            varchar(255) NOT NULL,
  text            varchar(255) NOT NULL,
  nickname        varchar(255) NOT NULL,
  image           varchar(255),
  token           varchar(255) NOT NULL,
  ts              timestamptz NOT NULL,
  num_connections integer NOT NULL,
  meta            text,
  user_id         integer,
  CONSTRAINT fk_messages_202605_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_messages_202605_user ON messages_202605 (user_id);

-- 운영 MySQL의 messages에는 user_id FK가 없다(rename 때 제약이 아카이브로 따라갔다).
CREATE TABLE messages (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz,
  ip              varchar(255) NOT NULL,
  type            varchar(255) NOT NULL,
  text            varchar(255) NOT NULL,
  nickname        varchar(255) NOT NULL,
  image           varchar(255),
  token           varchar(255) NOT NULL,
  ts              timestamptz NOT NULL,
  num_connections integer NOT NULL,
  meta            text,
  user_id         integer
);
CREATE INDEX idx_messages_user ON messages (user_id);

CREATE TABLE reactions (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  type       varchar(255) NOT NULL,
  nickname   varchar(255),
  ip         varchar(255) NOT NULL,
  post_id    integer,
  user_id    integer,
  reply_id   integer,
  message_id integer,
  CONSTRAINT fk_reactions_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE SET NULL,
  CONSTRAINT fk_reactions_reply FOREIGN KEY (reply_id) REFERENCES replies(id) ON DELETE SET NULL,
  -- 운영 MySQL과 동일하게 아카이브 테이블을 가리킨다. 의도적인 1:1 보존이므로
  -- 여기서 messages로 바꾸지 말 것 - 별개 작업이다.
  CONSTRAINT fk_reactions_message FOREIGN KEY (message_id) REFERENCES messages_202605(id) ON DELETE SET NULL
);
CREATE INDEX idx_reactions_post ON reactions (post_id);
CREATE INDEX idx_reactions_reply ON reactions (reply_id);
CREATE INDEX idx_reactions_message ON reactions (message_id);

-- ---------------------------------------------------------------- 온체인

CREATE TABLE blockchains (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  name        varchar(255) NOT NULL,
  symbol      varchar(255) NOT NULL,
  icon        varchar(255) NOT NULL,
  explore_url varchar(255),
  description varchar(255)
);

CREATE TABLE wallets (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  deleted_at    timestamptz,
  address       varchar(255) NOT NULL,
  memo          varchar(255),
  description   varchar(255),
  blockchain_id integer,
  balance       numeric(36,18),
  CONSTRAINT fk_wallets_blockchain FOREIGN KEY (blockchain_id) REFERENCES blockchains(id) ON DELETE SET NULL
);
CREATE INDEX idx_wallets_blockchain ON wallets (blockchain_id);

-- whale_alerts에는 id도 created_at/updated_at도 없다. PK는 hash다.
-- 운영에는 컬럼 구성이 완전히 동일한 인덱스가 둘(idx_amount_timestamp_owner,
-- idx_whale_main) 있고 PK와 중복인 unique 인덱스도 있었다. 하나만 남긴다.
CREATE TABLE whale_alerts (
  hash              varchar(255) PRIMARY KEY,
  amount            numeric(36,18),
  amount_usd        numeric(20,2),
  from_address      varchar(255),
  blockchain        varchar(255),
  symbol            varchar(255),
  from_owner        varchar(255),
  from_owner_type   varchar(255),
  to_address        varchar(255),
  to_owner          varchar(255),
  to_owner_type     varchar(255),
  transaction_count integer,
  transaction_type  varchar(255),
  "timestamp"       integer
);
CREATE INDEX idx_whale_main ON whale_alerts (amount_usd, "timestamp" DESC, from_owner_type, to_owner_type);

-- ---------------------------------------------------------------- 콘텐츠

CREATE TABLE images (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  key         varchar(255) NOT NULL,
  type        varchar(255),
  description varchar(255)
);

CREATE TABLE persons (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  name        varchar(255) NOT NULL,
  bio         text,
  description text,
  sharing_key varchar(255) NOT NULL
);
CREATE INDEX idx_persons_sharing_key ON persons (sharing_key);

CREATE TABLE persons_images (
  persons_id integer NOT NULL,
  images_id  integer NOT NULL,
  PRIMARY KEY (persons_id, images_id),
  CONSTRAINT fk_persons_images_person FOREIGN KEY (persons_id) REFERENCES persons(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_persons_images_image FOREIGN KEY (images_id) REFERENCES images(id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX idx_persons_images_person ON persons_images (persons_id);
CREATE INDEX idx_persons_images_image ON persons_images (images_id);

CREATE TABLE bad_words (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,
  type        varchar(255) NOT NULL DEFAULT 'insulting',
  word        varchar(255) NOT NULL,
  alternative varchar(255)
);

-- MySQL의 tinyint NOT NULL DEFAULT '0'을 boolean으로 옮긴다.
CREATE TABLE notifications (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  text       varchar(255) NOT NULL,
  type       varchar(255) NOT NULL,
  link       varchar(255),
  active     boolean NOT NULL DEFAULT false
);

CREATE TABLE price_predictions (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  deleted_at     timestamptz,
  user_id        integer,
  nickname       varchar(255) NOT NULL,
  ip             varchar(255),
  sharing_key    varchar(255),
  password       varchar(255),
  ticker         varchar(255) NOT NULL,
  price_snapshot numeric(36,18) NOT NULL,
  time_from      timestamptz,
  time_to        timestamptz,
  price_min      numeric(36,18),
  price_max      numeric(36,18)
);
CREATE INDEX idx_price_predictions_sharing_key ON price_predictions (sharing_key);

-- ---------------------------------------------------------------- 트리거

CREATE TRIGGER trg_users_updated_at             BEFORE UPDATE ON users             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_profiles_updated_at          BEFORE UPDATE ON profiles          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_auth_tokens_updated_at       BEFORE UPDATE ON auth_tokens       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_user_securities_updated_at   BEFORE UPDATE ON user_securities   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_banned_users_updated_at      BEFORE UPDATE ON banned_users      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_boards_updated_at            BEFORE UPDATE ON boards            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_posts_updated_at             BEFORE UPDATE ON posts             FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_replies_updated_at           BEFORE UPDATE ON replies           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_messages_updated_at          BEFORE UPDATE ON messages          FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_messages_202605_updated_at   BEFORE UPDATE ON messages_202605   FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_reactions_updated_at         BEFORE UPDATE ON reactions         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_blockchains_updated_at       BEFORE UPDATE ON blockchains       FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_wallets_updated_at           BEFORE UPDATE ON wallets           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_images_updated_at            BEFORE UPDATE ON images            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_persons_updated_at           BEFORE UPDATE ON persons           FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_bad_words_updated_at         BEFORE UPDATE ON bad_words         FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_notifications_updated_at     BEFORE UPDATE ON notifications     FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_price_predictions_updated_at BEFORE UPDATE ON price_predictions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
